name: Test Actions

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Echo test
        run: |
          echo "GitHub Actions is working!"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          ls -la
